 # 
 # Copyright (C) 2023 The Android Open Source Project 
 # Copyright (C) 2023 SebaUbuntu's TWRP device tree generator 
 # 
 # SPDX-License-Identifier: Apache-2.0 
 # 
  
 DEVICE_PATH := device/xiaomi/ruby 
  
 # For building with minimal manifest 
 ALLOW_MISSING_DEPENDENCIES := true 

# A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += \
    system \
    vendor \
    product \
    boot \
    vbmeta_vendor \
    vbmeta_system
BOARD_USES_RECOVERY_AS_BOOT := true
   
 # Architecture 
 TARGET_ARCH := arm64 
 TARGET_ARCH_VARIANT := armv8-a 
 TARGET_CPU_ABI := arm64-v8a 
 TARGET_CPU_ABI2 := 
 TARGET_CPU_VARIANT := generic 
 TARGET_CPU_VARIANT_RUNTIME := cortex-a55 

 TARGET_2ND_ARCH := arm 
 TARGET_2ND_ARCH_VARIANT := armv7-a-neon 
 TARGET_2ND_CPU_ABI := armeabi-v7a 
 TARGET_2ND_CPU_ABI2 := armeabi 
 TARGET_2ND_CPU_VARIANT := generic 
 TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55 
  
 # Power 
 ENABLE_CPUSETS := true 
 ENABLE_SCHEDBOOST := true 
  
 # Bootloader 
 PRODUCT_PLATFORM := mt6877 
 TARGET_BOOTLOADER_BOARD_NAME := ruby
 TARGET_NO_BOOTLOADER := true 
 TARGET_USES_UEFI := true 
  
 # Platform 
 TARGET_BOARD_PLATFORM := mt6877 

# Kernel 
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 
BOARD_KERNEL_IMAGE_NAME := Image 
BOARD_BOOTIMG_HEADER_VERSION := 2 
BOARD_KERNEL_BASE := 0x40078000 
BOARD_KERNEL_PAGESIZE := 2048 
BOARD_RAMDISK_OFFSET := 0x11088000 
BOARD_KERNEL_TAGS_OFFSET := 0x07c08000 
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION) 
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET) 
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET) 
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET) 

 # Kernel - prebuilt 
 TARGET_FORCE_PREBUILT_KERNEL := true 
 ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true) 
 TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel 
 endif 

 # Kernel dtb 
 BOARD_DTB_OFFSET := 0x07c08000 
 TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img 
 BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB) 
 BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET) 


 BOARD_INCLUDE_DTB_IN_BOOTIMG := true 
 TARGET_KERNEL_CONFIG := ruby_defconfig 
 TARGET_KERNEL_SOURCE := kernel/xiaomi/ruby  

 # Assert 
 TARGET_OTA_ASSERT_DEVICE := ruby,rubypro
  
 # Android Verified Boot 
 BOARD_AVB_ENABLE := true
 BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

 # VNDK Treble 
 BOARD_VNDK_VERSION := current 
  
 # Partitions 
 BOARD_BOOTIMAGE_PARTITION_SIZE := 134217728 
 BOARD_RECOVERYIMAGE_PARTITION_SIZE := 134217728

 # Dynamic Partition 
 BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64) 
 BOARD_SUPER_PARTITION_SIZE := 9126805504 
 BOARD_SUPER_PARTITION_GROUPS := xiaomi_dynamic_partitions 
 BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product mi_ext 
 BOARD_XIAOMI_DYNAMIC_PARTITIONS_SIZE := 9122611200

 # File systems 
 BOARD_HAS_LARGE_FILESYSTEM := true 
 BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4 
 BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4 
 BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4  
 TARGET_COPY_OUT_VENDOR := vendor 

 # System as root 
 BOARD_BUILD_SYSTEM_ROOT_IMAGE := false 
 BOARD_SUPPRESS_SECURE_ERASE := true 
   
 # Recovery 
 TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888" 
 TARGET_USERIMAGES_USE_EXT4 := true 
 TARGET_USERIMAGES_USE_F2FS := true
  
 # Display 
 TARGET_SCREEN_DENSITY := 440 
 TW_FRAMERATE := 60 
  
 # Crypto 
 TW_INCLUDE_CRYPTO := true 
 PLATFORM_VERSION := 14 
 PLATFORM_VERSION_LAST_STABLE := $(PLATFORM_VERSION) 
 PLATFORM_SECURITY_PATCH := 2099-12-31 
 VENDOR_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH) 
 BOOT_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH) 

 # System Properties 
 TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop 
  
 # Tool 
 TW_INCLUDE_REPACKTOOLS := true 
 TW_INCLUDE_RESETPROP := true 
 TW_INCLUDE_LIBRESETPROP := true 
 TW_INCLUDE_LPDUMP := true 
 TW_INCLUDE_LPTOOLS := true 
  
 # TWRP Configuration 
 TW_THEME := portrait_hdpi 
 ifeq ($(TW_DEVICE_VERSION),) 
 TW_DEVICE_VERSION=ruby
 endif 
 RECOVERY_SDCARD_ON_DATA := true 
 TW_EXCLUDE_DEFAULT_USB_INIT := true 
 TW_EXTRA_LANGUAGES := true 
 TW_INCLUDE_NTFS_3G := true 
 TARGET_USES_MKE2FS := true 
 TW_USE_TOOLBOX := true 
 TW_INPUT_BLACKLIST := "hbtp_vm" 
 TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness" 
 TW_MAX_BRIGHTNESS := 2047 
 TW_DEFAULT_BRIGHTNESS := 200 
 TW_NO_SCREEN_BLANK := true 
 TW_EXCLUDE_APEX := true 
  
 # Debug 
 TWRP_INCLUDE_LOGCAT := true 
 TARGET_USES_LOGD := true 
  
 
